import type { Metadata } from 'next'
import { Poppins, Kaushan_Script } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'], variable: '--poppins' })
const kashua = Kaushan_Script({ weight: ['400'], subsets: ['latin'], variable: '--kashua' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body className={`${poppins.variable} ${kashua.variable}`}>{children}</body>
    </html>
  )
}
